import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import StoreProvider from './redux/StoreProvider';
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Yellow Network",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={montserrat.className}>
        <StoreProvider>
          <ToastContainer position="top-right" autoClose={5000} hideProgressBar={false} newestOnTop closeOnClick pauseOnFocusLoss draggable pauseOnHover />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
